### PR TITLE
feat: add backend plugin to make alerting possible

### PR DESCRIPTION
**Pull request by stanvanrooy**
This PR implements the backend part of the plugin. This makes it possible to, for example, create alerts in Grafana, based on data retrieved from Parseable.

Example of creating an alert:

https://github.com/parseablehq/parseable-datasource/assets/49564025/41cd6e5a-5131-48a4-8d6f-69513b05c7aa

Let me know if you have any questions!

### CODE REVIEW

**Comment by nitisht** [comment]
This looks great @stanvanrooy . Does this in any way work with the Parseable alerts? or this is completely independent

**Comment by stanvanrooy** [comment]
@nitisht, I am not very familiar with the native Parseable alerts, but from a quick look it seems quite similar to Grafana alerts, so I don't think they can work together.

You can use both for querying data, setting conditions for when the alert should trigger & configuring when and who should be notified once the alert is triggered.

**Comment by nitisht** [comment]
Thanks. That should be fine - do you mind adding step to setup alerts for Grafana in the readme please. We can then take this in.

**Comment by stanvanrooy** [comment]
Of course :) What exactly should I describe in there? There aren't any special steps required to get it to work with parseable & the rest is all native Grafana.

**Comment by nitisht** [comment]
> Of course :) What exactly should I describe in there? There aren't any special steps required to get it to work with parseable & the rest is all native Grafana.

Hmm, okay let me merge this then. I'll set it up once and try to set up / guidance docs around this for people new to Grafana + Parseable.

**Pull request merged**
